# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 18:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True
	
	dependencies = [
	]
	
	operations = [
	]
