# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kannji_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('kanji_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('literal', models.CharField(max_length=1)),
                ('stroke_count', models.PositiveSmallIntegerField()),
                ('jlpt_level', models.PositiveSmallIntegerField()),
                ('school_grade', models.PositiveSmallIntegerField()),
                ('frequency', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KanjiMeanings',
            fields=[
                ('meaning_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('meaning', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(blank=True, max_length=7, null=True)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanji_meanings_set', to='kannji_api.Kanji')),
            ],
        ),
        migrations.CreateModel(
            name='KanjiRadicals',
            fields=[
                ('radical_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('radical', models.PositiveSmallIntegerField()),
                ('type', models.CharField(max_length=20)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanji_radicals_set', to='kannji_api.Kanji')),
            ],
        ),
        migrations.CreateModel(
            name='KanjiReadings',
            fields=[
                ('reading_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reading', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=7)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanji_readings_set', to='kannji_api.Kanji')),
            ],
        ),
        migrations.CreateModel(
            name='LearningLists',
            fields=[
                ('list_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=300, null=True)),
                ('kanji', models.ManyToManyField(to='kannji_api.Kanji')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='kanjireadings',
            unique_together=set([('kanji', 'reading', 'type'), ('reading_id', 'kanji')]),
        ),
        migrations.AlterUniqueTogether(
            name='kanjiradicals',
            unique_together=set([('kanji', 'radical', 'type'), ('radical_id', 'kanji')]),
        ),
        migrations.AlterUniqueTogether(
            name='kanjimeanings',
            unique_together=set([('kanji', 'meaning', 'language'), ('meaning_id', 'kanji')]),
        ),
    ]
