# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kannji_api', '0002_auto_20170411_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='frequency',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='jlpt_level',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='school_grade',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='kanjimeanings',
            name='language',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='kanjimeanings',
            name='meaning',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learninglists',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='learninglists',
            name='thumbnail_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
