# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kannji_api', '0003_auto_20170411_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiragana',
            fields=[
                ('kana_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('literal', models.CharField(editable=False, max_length=2)),
                ('transliteration', models.CharField(max_length=4)),
                ('type', models.CharField(choices=[('MO', 'Monograph'), ('DC', 'Diacritic'), ('DG', 'Digraph'), ('DD', 'Diacritic-Digraph')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Katakana',
            fields=[
                ('kana_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('literal', models.CharField(editable=False, max_length=2)),
                ('transliteration', models.CharField(max_length=4)),
                ('type', models.CharField(choices=[('MO', 'Monograph'), ('DC', 'Diacritic'), ('DG', 'Digraph'), ('DD', 'Diacritic-Digraph')], max_length=2)),
                ('corresponding_hiragana', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='kannji_api.Hiragana')),
                ('diacritic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diacritic_uuid', to='kannji_api.Katakana')),
                ('digraph', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digraph_uuid', to='kannji_api.Katakana')),
                ('monograph', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monograph_uuid', to='kannji_api.Katakana')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hiragana',
            name='corresponding_katakana',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='kannji_api.Katakana'),
        ),
        migrations.AddField(
            model_name='hiragana',
            name='diacritic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diacritic_uuid', to='kannji_api.Hiragana'),
        ),
        migrations.AddField(
            model_name='hiragana',
            name='digraph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digraph_uuid', to='kannji_api.Hiragana'),
        ),
        migrations.AddField(
            model_name='hiragana',
            name='monograph',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monograph_uuid', to='kannji_api.Hiragana'),
        ),
    ]
